package app.windows;

import org.jfree.data.category.DefaultCategoryDataset;
import app.control.ChatData;
import app.elements.ChatDay;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;

/**
 *
 * @author Luigi Salcedo
 */
public class ChatStats extends javax.swing.JFrame 
{
    private BufferedImage comparationImage;
    
    public ChatStats() 
    {      
        DefaultCategoryDataset dayMessagesData = new DefaultCategoryDataset(); 
        
        for(ChatDay day : ChatData.chatDays)
        {
            dayMessagesData.setValue(day.getMessages().size(), "Messages", day.getDate());
        }
        
        JFreeChart dayMessagesComparation = ChartFactory.createBarChart("Comparison of messages per day", "Dates", "Messages", dayMessagesData);
        
        comparationImage = dayMessagesComparation.createBufferedImage(1000, 500);
        
        initComponents();
        
        pack();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comparationArea = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        comparationArea.setIcon(new ImageIcon(comparationImage));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(comparationArea)
                .addContainerGap(610, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comparationArea)
                .addContainerGap(320, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel comparationArea;
    // End of variables declaration//GEN-END:variables
}
