package app.windows;

import app.control.ChatData;
import app.elements.ChatDay;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author Luigi Salcedo
 */
public class MainWindow extends javax.swing.JFrame 
{    
    public MainWindow() 
    {
        initComponents();
        loadComboBoxElements();
        loadSettings();
    }
    
    private void loadComboBoxElements()
    {   
        for(ChatDay day : ChatData.chatDays)
        {
            daySelectionerBox.addItem(day.toString());
        }
    }
    
    private void loadSettings()
    {
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        addWindowListener(new WindowAdapter()
                {
                    @Override
                    public void windowClosing(WindowEvent e)
                    {
                        FileSelection.fs.setVisible(true);
                    }
                });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        daySelectionerBox = new javax.swing.JComboBox<>();
        scrollTextArea = new javax.swing.JScrollPane();
        chatTextArea = new javax.swing.JTextArea();
        showMessagesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chat");
        setBackground(new java.awt.Color(231, 255, 229));

        daySelectionerBox.setBackground(new java.awt.Color(231, 255, 229));
        daySelectionerBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        daySelectionerBox.setMaximumRowCount(20);
        daySelectionerBox.setToolTipText("");
        daySelectionerBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        daySelectionerBox.setFocusable(false);
        daySelectionerBox.setLightWeightPopupEnabled(false);
        daySelectionerBox.setRequestFocusEnabled(false);
        daySelectionerBox.setVerifyInputWhenFocusTarget(false);
        daySelectionerBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daySelectionerBoxActionPerformed(evt);
            }
        });

        scrollTextArea.setBackground(new java.awt.Color(0, 0, 0));
        scrollTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrollTextArea.setFocusable(false);

        chatTextArea.setColumns(20);
        chatTextArea.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        chatTextArea.setRows(5);
        chatTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chatTextArea.setFocusable(false);
        scrollTextArea.setViewportView(chatTextArea);

        showMessagesButton.setBackground(new java.awt.Color(231, 255, 229));
        showMessagesButton.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        showMessagesButton.setText("Select day");
        showMessagesButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        showMessagesButton.setFocusable(false);
        showMessagesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMessagesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTextArea)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(daySelectionerBox, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showMessagesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 581, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(daySelectionerBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showMessagesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void daySelectionerBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daySelectionerBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daySelectionerBoxActionPerformed

    private void showMessagesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMessagesButtonActionPerformed
        String daySelectedDate = (String)daySelectionerBox.getSelectedItem();
        
        ChatDay daySelected = ChatData.chatDaysHash.get(daySelectedDate);
        
        StringBuilder sb = new StringBuilder();
        
        for(String message : daySelected.getMessages())
        {
            sb.append(message).append("\n");
        }
        
        chatTextArea.setText(sb.toString());
        
    }//GEN-LAST:event_showMessagesButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chatTextArea;
    private javax.swing.JComboBox<String> daySelectionerBox;
    private javax.swing.JScrollPane scrollTextArea;
    private javax.swing.JButton showMessagesButton;
    // End of variables declaration//GEN-END:variables
}
